Name = input("whats your name?:")
Age = input("whats your Age?:")
favouritefood = input("whats your favourite food:")
favouritemusic= input("whats your favourite music and Musician?:")
Area = input("where do you live?:")
print("You are")
print(Name)
print("You are " + Age + " old")
print("You're probably hungry for")
print(favouritefood)
print("and you're definitely getting on to")
print(favouritemusic)
print("living in the amazing")
print(Area)